name: Build

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-14, macos-15]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sh -ex test/deps.sh
      - name: Build
        run: cd src; make
#     - name: Test
#       run: cd test; ./test.sh
